"""Read-only endpoint that serves model evaluation metrics from the
results/ folder bundled alongside the backend.  No auth required so
the public demo page works even before login.
"""
import json
import os
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, JSONResponse

router = APIRouter(prefix="/model", tags=["model"])

_RESULTS_DIR = Path(__file__).resolve().parents[4] / "results"


def _results_path(filename: str) -> Path:
    """Return resolved path inside results/, rejecting path traversal."""
    resolved = (_RESULTS_DIR / filename).resolve()
    if not str(resolved).startswith(str(_RESULTS_DIR.resolve())):
        raise HTTPException(status_code=404, detail="Not found")
    return resolved


@router.get("/metrics")
async def get_model_metrics():
    """Return the evaluation JSON generated by evaluate.py."""
    json_path = _results_path("model.evaluation.json")
    if not json_path.exists():
        raise HTTPException(status_code=404, detail="Evaluation results not found. Run evaluate.py first.")
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return JSONResponse(content=data)


@router.get("/metrics/chart/{chart_name}")
async def get_metrics_chart(chart_name: str):
    """Serve confusion_matrix.png or metrics_chart.png from results/."""
    allowed = {"confusion_matrix.png", "metrics_chart.png"}
    if chart_name not in allowed:
        raise HTTPException(status_code=404, detail="Chart not found")
    path = _results_path(chart_name)
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"{chart_name} not found")
    return FileResponse(str(path), media_type="image/png")
